import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SWRProvider from "@/components/SWRProvider";
import BottomNavigationBar from "@/components/BottomNavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Habit Tracker",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="mx-auto max-w-md bg-white dark:bg-white">
            <body
                className={`${inter.className} min-h-screen shadow-2xl bg-white`}
            >
                <SWRProvider>
                    {children}
                    <BottomNavigationBar />
                </SWRProvider>
            </body>
        </html>
    );
}
