import { Habit } from "./types";

export const mockHabits: Habit[] = [
    {
        id: 1,
        displayName: "Morning Run",
        iconName: "run_icon",
        type: "do",
        frequencyType: "daily",
        reminderTime: "07:00",
        isReminderOn: true,
        goalValue: 5,
        goalUnit: "km",
        isActive: true,
        createdAt: "2024-12-01T10:00:00Z",
    },
    {
        id: 2,
        displayName: "Read a Book",
        iconName: "read_icon",
        type: "do",
        frequencyType: "daily",
        reminderTime: "19:00",
        isReminderOn: true,
        goalValue: 30,
        goalUnit: "minutes",
        isActive: true,
        createdAt: "2024-12-01T10:00:00Z",
    },
    {
        id: 3,
        displayName: "Meditation",
        iconName: "meditation_icon",
        type: "do",
        frequencyType: "daily",
        reminderTime: "21:00",
        isReminderOn: true,
        goalValue: 15,
        goalUnit: "minutes",
        isActive: true,
        createdAt: "2024-12-01T10:00:00Z",
    },
    {
        id: 4,
        displayName: "Drink Water",
        iconName: "water_icon",
        type: "do",
        frequencyType: "daily",
        isReminderOn: false,
        goalValue: 2,
        goalUnit: "liters",
        isActive: true,
        createdAt: "2024-12-01T10:00:00Z",
    },
];
